// config.js
// UPDATED: 4.17.26 @ 2:00PM

export const CFG = {
  // ── STRUCTURE ────────────────────────────────────────
  TENTACLE_COUNT:               8,
  TENTACLE_SEGMENTS:            12,
  TENTACLE_SEGMENT_LENGTH:     11.5,
  TENTACLE_BASE_WIDTH:         4,
  // ── MOTION ──────────────────────────────────────────
  TENTACLE_CURL_STRENGTH:    0.14,
  TENTACLE_MAX_BEND:     Math.PI / 3,
  TENTACLE_ANCHOR_SWAY:         0.5,
  TENTACLE_WANDER_SPEED:     0.01,   //PLACEHOLDER
  // ── ANCHORING ───────────────────────────────────────
  TENTACLE_ANCHOR_RADIUS:      10.5,
  TENTACLE_ANCHOR_Y_OFFSET:    19.5,
  // ── TIP PHYSICS ─────────────────────────────────────
  TENTACLE_TIP_GRAVITY:        160,
  TENTACLE_TIP_STIFFNESS:       7.5,
  TENTACLE_TIP_DRAG:         0.86,
  TENTACLE_TIP_BIAS:           65,
  TENTACLE_REACH:             120,   //PLACEHOLDER
  TENTACLE_TIP_REPEL_RADIUS:   15,
  TENTACLE_TIP_REPEL_STRENGTH: 500,
  TENTACLE_REPEL_RADIUS:       20,
  TENTACLE_REPEL_STRENGTH:     500,
  SPLINE_COLOR:          '#44004d',
  GLOW_COLOR:            '#aa05ad',
  SIZE:                        80,
};

export const DEFAULTS = Object.freeze({ ...CFG });

export const TANK = Object.freeze({
  SEGMENT_BUDGET: 600,
  MAX_CREATURES:  25,
});


export const HEAD_CONFIGS = [
  {
    name: 'Cirrus tranquillus', // NAME NOT FINALIZED - ONCE traits.js IS COMPLETED, NAMES WILL BE REVISED TO MATCH THEIR TRAITS: Cirrus tranquillus = whispy + chill 
    cfg: {
      TENTACLE_COUNT: 4, // NON-AGGRESSIVE / CHILL
      TENTACLE_SEGMENTS: 8,
      TENTACLE_SEGMENT_LENGTH: 19.50,
      TENTACLE_BASE_WIDTH: 2.50, // THIN / WHISPY
      TENTACLE_CURL_STRENGTH: 0.15,
      TENTACLE_MAX_BEND: Math.PI * 0.433,  // ~78°
      TENTACLE_ANCHOR_SWAY: 0.50,
      TENTACLE_ANCHOR_RADIUS: 9.50,
      TENTACLE_ANCHOR_Y_OFFSET: 22.00,
      TENTACLE_TIP_GRAVITY: 173,
      TENTACLE_TIP_STIFFNESS: 11.00,
      TENTACLE_TIP_DRAG: 0.94,
      TENTACLE_TIP_BIAS: 35,
      TENTACLE_TIP_REPEL_RADIUS: 25,
      TENTACLE_TIP_REPEL_STRENGTH: 320,
      TENTACLE_REPEL_RADIUS: 15,
      TENTACLE_REPEL_STRENGTH: 625,
      SIZE: 66,
      SPLINE_COLOR: '#646175',
      GLOW_COLOR:   '#786ec4',
    },
  },
  {
    name: 'Amethystus curiosus', // NAME NOT FINALIZED - ONCE traits.js IS COMPLETED, NAMES WILL BE REVISED TO MATCH THEIR TRAITS: Amethystus curiosus = amethyst/purple + curious 
    cfg: {
      TENTACLE_COUNT:              6, // HIGHER THENTACLE COUNT THAN THE OTHER ONE BUT NOT QUITE AT 8 SO IT's CURIOUS BUT  NOT A COMPLETE SOCIAL BUTTERFLY
      TENTACLE_SEGMENTS:           12,
      TENTACLE_SEGMENT_LENGTH:     11.5,
      TENTACLE_BASE_WIDTH:         4,
      TENTACLE_CURL_STRENGTH:      0.14,
      TENTACLE_MAX_BEND:           Math.PI / 3,
      TENTACLE_ANCHOR_SWAY:        0.5,
      TENTACLE_WANDER_SPEED:       0.01,
      TENTACLE_ANCHOR_RADIUS:      10.5,
      TENTACLE_ANCHOR_Y_OFFSET:    19.5,
      TENTACLE_TIP_GRAVITY:        160,
      TENTACLE_TIP_STIFFNESS:      7.5,
      TENTACLE_TIP_DRAG:           0.86,
      TENTACLE_TIP_BIAS:           65,
      TENTACLE_REACH:              120,
      TENTACLE_TIP_REPEL_RADIUS:   15,
      TENTACLE_TIP_REPEL_STRENGTH: 500,
      TENTACLE_REPEL_RADIUS:       20,
      TENTACLE_REPEL_STRENGTH:     500,
      SIZE:                        80,
      SPLINE_COLOR:                '#44004d', // PURPLE-ISH -> Amethystus
      GLOW_COLOR:                  '#aa05ad',
    },
  },
    {
    name: 'Pusillus anxius', // NAME NOT FINALIZED - ONCE traits.js IS COMPLETED, NAMES WILL BE REVISED TO MATCH THEIR TRAITS: Pusillus anxius = small + anxious 
    cfg: {
      TENTACLE_COUNT: 4,
      TENTACLE_SEGMENTS: 8,
      TENTACLE_SEGMENT_LENGTH: 9.50,
      TENTACLE_BASE_WIDTH: 3.50,
      TENTACLE_CURL_STRENGTH: 0.21,
      TENTACLE_MAX_BEND: Math.PI * 0.389,  // ~70°
      TENTACLE_ANCHOR_SWAY: 0.50,
      TENTACLE_ANCHOR_RADIUS: 8.50,
      TENTACLE_ANCHOR_Y_OFFSET: 16.50,
      TENTACLE_TIP_GRAVITY: 61,
      TENTACLE_TIP_STIFFNESS: 10.00,
      TENTACLE_TIP_DRAG: 0.94,
      TENTACLE_TIP_BIAS: 72,
      TENTACLE_TIP_REPEL_RADIUS: 25,
      TENTACLE_TIP_REPEL_STRENGTH: 290,
      TENTACLE_REPEL_RADIUS: 46,
      TENTACLE_REPEL_STRENGTH: 445,
      SIZE: 59,
      SPLINE_COLOR: '#670184',
      GLOW_COLOR:   '#9a6dee',
    },
  },
      {
    name: 'Crassus tristis', // NAME NOT FINALIZED - ONCE traits.js IS COMPLETED, NAMES WILL BE REVISED TO MATCH THEIR TRAITS: Crassus tristis = thick + gloomy
    cfg: {
      TENTACLE_COUNT: 3,
      TENTACLE_SEGMENTS: 7,
      TENTACLE_SEGMENT_LENGTH: 14.50,
      TENTACLE_BASE_WIDTH: 9.50,
      TENTACLE_CURL_STRENGTH: 0.04,
      TENTACLE_MAX_BEND: Math.PI / 3,  // ~56°
      TENTACLE_ANCHOR_SWAY: 0.00,
      TENTACLE_ANCHOR_RADIUS: 10.00,
      TENTACLE_ANCHOR_Y_OFFSET: 16.00,
      TENTACLE_TIP_GRAVITY: 132,
      TENTACLE_TIP_STIFFNESS: 3.00,
      TENTACLE_TIP_DRAG: 0.85,
      TENTACLE_TIP_BIAS: 50,
      TENTACLE_TIP_REPEL_RADIUS: 40,
      TENTACLE_TIP_REPEL_STRENGTH: 150,
      TENTACLE_REPEL_RADIUS: 25,
      TENTACLE_REPEL_STRENGTH: 300,
      SIZE: 83,
      SPLINE_COLOR: '#656a86',
      GLOW_COLOR:   '#435784',
    },
  },
      {
    name: 'Singulus iracundus', // NAME NOT FINALIZED - ONCE traits.js IS COMPLETED, NAMES WILL BE REVISED TO MATCH THEIR TRAITS: Singulus iracundus = single (one tentace) + angry  
    cfg: {
      TENTACLE_COUNT: 1,
      TENTACLE_SEGMENTS: 10,
      TENTACLE_SEGMENT_LENGTH: 15.00,
      TENTACLE_BASE_WIDTH: 9.50,
      TENTACLE_CURL_STRENGTH: 0.22,
      TENTACLE_MAX_BEND: Math.PI / 4,  // ~40°
      TENTACLE_ANCHOR_SWAY: 1.00,
      TENTACLE_ANCHOR_RADIUS: 0.00,
      TENTACLE_ANCHOR_Y_OFFSET: 25.00,
      TENTACLE_TIP_GRAVITY: 250,
      TENTACLE_TIP_STIFFNESS: 24.50,
      TENTACLE_TIP_DRAG: 0.99,
      TENTACLE_TIP_BIAS: 0,
      TENTACLE_TIP_REPEL_RADIUS: 10,
      TENTACLE_TIP_REPEL_STRENGTH: 50,
      TENTACLE_REPEL_RADIUS: 50,
      TENTACLE_REPEL_STRENGTH: 300,
      SIZE: 83,
      SPLINE_COLOR: '#6e4f72',
      GLOW_COLOR:   '#b14e92',
        },
  },
      {
    name: 'Horridus Curiosus', // NAME NOT FINALIZED - ONCE traits.js IS COMPLETED, NAMES WILL BE REVISED TO MATCH THEIR TRAITS: Horridus Curiosus = creepy + curious 
    cfg: {
      TENTACLE_COUNT: 5,
      TENTACLE_SEGMENTS: 8,
      TENTACLE_SEGMENT_LENGTH: 13.50,
      TENTACLE_BASE_WIDTH: 5.50,
      TENTACLE_CURL_STRENGTH: 0.18,
      TENTACLE_MAX_BEND: Math.PI / 4,  // ~45°
      TENTACLE_ANCHOR_SWAY: 0.00,
      TENTACLE_ANCHOR_RADIUS: 13.00,
      TENTACLE_ANCHOR_Y_OFFSET: 15.00,
      TENTACLE_TIP_GRAVITY: 164,
      TENTACLE_TIP_STIFFNESS: 14.00,
      TENTACLE_TIP_DRAG: 0.96,
      TENTACLE_TIP_BIAS: 42,
      TENTACLE_TIP_REPEL_RADIUS: 64,
      TENTACLE_TIP_REPEL_STRENGTH: 395,
      TENTACLE_REPEL_RADIUS: 17,
      TENTACLE_REPEL_STRENGTH: 70,
      SIZE: 83,
      SPLINE_COLOR: '#482b50',
      GLOW_COLOR:   '#6786c9',
    },
  }
];